version: '3.7' # version del docker-compose(?)
services:
  web: # 1er servicio: nginx
    image: nginx:stable # imagen de docker hub que vamos a usar
    container_name: nginx # nombre para referirse al servicio
    ports:
      - 80:80 # puerto de mi pc:puerto del servicio
    volumes:
      - ./src:/var/www/html # carpeta local/ vincula a carpeta de nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # archivo local / reflejado en archivo de la imagen
    depends_on: # para correr este servicio debe estar corriendo php y mysql antes
      - php
    networks: # la red que los conecta se llama laravel
      - laravel

  php: # 3er servicio
    build: # este se construira aqui mismo
      context: . # ruta de referencia ./
      dockerfile: Dockerfile # nombre del archivo de configuracion de la imagen
    container_name: php #
    volumes: # carpeta de proyecto local : carpeta del container que da vida a los archivos PHP
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel # red

networks: # declaracion de la red
  laravel:
